package common

import (
	"testing"

	"github.com/lemconn/exlink/types"
)

func TestGenerateClientOrderID(t *testing.T) {
	exchanges := []struct {
		name     string
		exchange string
		side     types.OrderSide
	}{
		{"OKX Buy", "okx", types.OrderSideBuy},
		{"OKX Sell", "okx", types.OrderSideSell},
		{"Binance Buy", "binance", types.OrderSideBuy},
		{"Binance Sell", "binance", types.OrderSideSell},
		{"Bybit Buy", "bybit", types.OrderSideBuy},
		{"Bybit Sell", "bybit", types.OrderSideSell},
		{"Gate Buy", "gate", types.OrderSideBuy},
		{"Gate Sell", "gate", types.OrderSideSell},
	}

	ids := make(map[string]string)
	
	for _, tt := range exchanges {
		t.Run(tt.name, func(t *testing.T) {
			id := GenerateClientOrderID(tt.exchange, tt.side)
			ids[tt.name] = id
			t.Logf("%s: %s", tt.name, id)
		})
	}

	// Print all generated IDs
	t.Log("\n=== Generated Order IDs ===")
	for name, id := range ids {
		t.Logf("%-20s: %s", name, id)
	}

	// Verify all IDs are different
	uniqueIDs := make(map[string]bool)
	for name, id := range ids {
		if uniqueIDs[id] {
			t.Errorf("Duplicate ID found: %s (generated by %s)", id, name)
		}
		uniqueIDs[id] = true
	}
}
