package common

import (
	"testing"

	"github.com/lemconn/exlink/option"
)

func TestGenerateClientOrderID(t *testing.T) {
	exchanges := []struct {
		name     string
		exchange string
		side     option.SpotOrderSide
	}{
		{"OKX Buy", "okx", option.Buy},
		{"OKX Sell", "okx", option.Sell},
		{"Binance Buy", "binance", option.Buy},
		{"Binance Sell", "binance", option.Sell},
		{"Bybit Buy", "bybit", option.Buy},
		{"Bybit Sell", "bybit", option.Sell},
		{"Gate Buy", "gate", option.Buy},
		{"Gate Sell", "gate", option.Sell},
	}

	ids := make(map[string]string)

	for _, tt := range exchanges {
		t.Run(tt.name, func(t *testing.T) {
			id := GenerateClientOrderID(tt.exchange, tt.side.ToSide())
			ids[tt.name] = id
			t.Logf("%s: %s", tt.name, id)
		})
	}

	// Print all generated IDs
	t.Log("\n=== Generated Order IDs ===")
	for name, id := range ids {
		t.Logf("%-20s: %s", name, id)
	}

	// Verify all IDs are different
	uniqueIDs := make(map[string]bool)
	for name, id := range ids {
		if uniqueIDs[id] {
			t.Errorf("Duplicate ID found: %s (generated by %s)", id, name)
		}
		uniqueIDs[id] = true
	}
}
